### ISSUE TITLE
Link in README 404s

### ISSUE THREAD

**Issue by dvisztempacct** [k4b7/ast-editor#2]
Any chance this could be revived?

Thanks

http://kevinb7.github.io/ast-editor/

**Comment by kevinbarabash** [comment]
I can fix the link.  In terms of reviving this project, I've moved on to other things.  Making this work for JS is complicated because JS has a lot of different syntax to handle.

**Comment by k4b7** [comment]
I've fixed the link.

**Comment by dvisztempacct** [comment]
I'm not terribly interested in using this for Javascript. Are you working or aware of a similar project for other languages?
